<?xml version="1.0"?>
<robot name="selfie" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- inertial parameter macros -->



<xacro:macro name="chassis_inertial_params">
  <origin xyz="${chassis_x/2} 0 0" rpy="0 0 0" />
  <mass value="${chassis_mass}" />
  <inertia ixx="${chassis_mass*(chassis_y*chassis_y + chassis_z*chassis_z)/12}" ixy="0"          ixz="0"
                          iyy="${chassis_mass*(chassis_x*chassis_x + chassis_z*chassis_z)/12}"   iyz="0"
                                           izz="${chassis_mass*(chassis_y*chassis_y + chassis_x*chassis_x)/12}" />
</xacro:macro>

<xacro:macro name="wheel_inertial_params">
  <origin xyz="0 0 0" rpy="0 0 0" />
  <mass value="${wheel_mass}" />
  <inertia ixx="${wheel_mass*(3*wheel_radius*wheel_radius+wheel_width*wheel_width)/12}" ixy="0"          ixz="0"
                            iyy="${wheel_mass*(3*wheel_radius*wheel_radius+wheel_width*wheel_width)/12}" iyz="0"
                                             izz="${wheel_mass*wheel_radius*wheel_radius/2}" />
</xacro:macro>


<xacro:macro name="steering_hinge_inertial_params">
  <origin xyz="0 0 0" rpy="0 0 0" />
  <mass value="${hinge_mass}" />
  <inertia ixx="${2*hinge_mass*hinge_radius*hinge_radius/3}" ixy="0"           ixz="0"
                            iyy="${2*hinge_mass*hinge_radius*hinge_radius/3}"  iyz="0"
                                              izz="${2*hinge_mass*hinge_radius*hinge_radius/3}" />
</xacro:macro>

<xacro:macro name="hokuyo_inertial_params">
  <origin xyz="0 0 0" rpy="0 0 0" />
  <mass value="0.130" />
  <inertia ixx="4E-06" ixy="0"           ixz="0"
                            iyy="4E-06"  iyz="0"
                                              izz="4E-06" />
</xacro:macro>


<!-- geometry macros -->

<xacro:macro name="chassis_geometry">
  <origin xyz="${chassis_x/2} 0 0" rpy="0 0 0" /> <!-- origin xyz="-0.08 0 0" rpy="0 0 0"-->
  <geometry>
    <mesh filename="package://gazebo_selfie_sim/vehicles/models/selfie/meshes/my_chasis.STL"/>
  </geometry>
</xacro:macro>


<xacro:macro name="wheel_geometry">
  <origin xyz="0 0 0.0" rpy="0 0 0" />
  <geometry>
    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
  </geometry>
</xacro:macro>
<!-- transmission macros -->

<xacro:macro name="wheel_transmission" params="name">
  <transmission name="${name}_transmission" type="SimpleTransmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${name}_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="${name}_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</xacro:macro>

<xacro:macro name="steering_hinge_transmission" params="name">
  <transmission name="${name}_transmission" type="SimpleTransmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${name}_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="${name}_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</xacro:macro>

</robot>
